# Generated by Django 4.2.4 on 2023-09-19 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('missingperson', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='missingperson',
            name='identification_marks',
        ),
    ]
